<?php

namespace AppBundle\Repository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends \Doctrine\ORM\EntityRepository
{
	public function searchByWordsInResume($word)
	{
		$qb = $this->createQueryBuilder('a');

		$query = $qb->select('a')
		            ->where('a.bio LIKE :word')
		            ->setParameter('word', '%'.$word.'%')
		            ->getQuery();

		$results = $query->getArrayResult();

		return $results;
	}
}
